### ISSUE TITLE
Is there a pretrained model?

### ISSUE THREAD

**Issue by ruohoruotsi** [dhimasryan/MTI-Net#1]
Hiya, thank you for the nice series of papers on speech intelligibility (STOI-Net, MOSA-Net, MTI-Net). I'm curious if there a pretrained model for MTI-Net? Cheers

**Comment by dhimasryan** [comment]
Hi, please kindly refer to the following [link](https://github.com/dhimasryan/MTI-Net/tree/main/Pretrained_Model) for the pre-trained model. Please also noted that we trained the model on the Mandarin dataset. Thanks

**Comment by ruohoruotsi** [comment]
Thank you very much sir!
